void __EntryFunction__()
{
	if (SCRIPTS::_DOES_COMPRESSED_GLOBAL_BLOCK_BUFFER_EXIST(3))
	{
		SCRIPTS::_RESTORE_GLOBAL_BLOCK(3);
	}
	else
	{
		SCRIPTS::_STORE_GLOBAL_BLOCK(3);
	}
	SCRIPTS::TERMINATE_THIS_THREAD();
}

